name: sysfoo-ci-pipeline
on:
  push:
    branches:
      - master

jobs:
  build-sysfoo:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout or Code Clone
        uses: actions/checkout@v4

      - name: Run mvn test
        run: mvn test

      - name: Run mvn clean & mvn package
        run: mvn clean package

      - name: Run ls command
        run: ls -lrt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sysfoo
          path: target/sysfoo.war
